In [5]:
# # Drive Mount 실행후 로그인하고 임의의 새로운 폴더를 생성해주세요
# from google.colab import drive

# drive.mount("/content/drive")

#서울특별시 유기동물 현황 확인하기

##1.공공데이터 수집하기
#####(1) data.seoul.go.kr 접속
#####(2) "서울시 유기동물보호현황 통계" 검색
#####(3) excel(셀병합 해제), csv, txt 각각 다운로드하여 저장
#####(4) colab 왼쪽에 파일을 클릭하여 생성한 폴더에 모두 업로드

##2.데이터 읽어오기

###(1)정형 데이터를 관리하기 위한 라이브러리 선언하기

In [6]:
# 라이브러리 선언
# import pandas as pd

import pandas as pd

###(2)excel 화일(유기동물보호현황.xlsx) 읽고 데이터 확인하기

In [13]:
# 변수명 = pd.read_excel('파일경로명', 속성들)
excelData = pd.read_excel("유기동물보호현황.xlsx")
print(excelData)

    자치구별(1)  자치구별(2)    시점    합계    합계.1  합계.2   합계.3  합계.4  합계.5    합계.6  \
0   자치구별(1)  자치구별(2)    시점     개       개     개      개     개   고양이     고양이
1   자치구별(1)  자치구별(2)    시점    소계  인도(주인)  입양분양  폐사안락사  계류기증    소계  인도(주인)
2        합계       소계  2021  2784    1260  1110    341    73  2526      72
3        합계       소계  2022  2491    1110   814    536    31  2134      56
4        합계      종로구  2021    92      24    43     19     6    94       -
5        합계      종로구  2022    79      28    22     29     -   103       1
6        합계       중구  2021    32      20     5      5     2    56       -
7        합계       중구  2022    36      19    10      7     -    47       1
8        합계      용산구  2021   112      80    30      1     1   146       5
9        합계      용산구  2022   118      79    33      5     1   115      11
10       합계      성동구  2021    75      25    36     13     1    77       -
11       합계      성동구  2022    70      34    17     19     -    91       3
12       합계      광진구  2021    73      35    28     10     -    77       1
13       합계      광진구  2022    67      33    27      7     -    96       2
14       합계     동대문구  2021   100      40    47     11     2    90       -
15       합계     동대문구  2022    94      34    41     18     1    99       3
16       합계      중랑구  2021   107      48    41     12     6   109      14
17       합계      중랑구  2022   102      48    35     16     3    84       -
18       합계      성북구  2021   175      64    82     26     3    48       1
19       합계      성북구  2022   115      48    35     32     -    44       1
20       합계      강북구  2021   166      67    62     34     3    72       1
21       합계      강북구  2022   162      56    63     43     -    91       -
22       합계      도봉구  2021   101      47    37     17     -    55       -
23       합계      도봉구  2022    82      45    24     13     -    47       3
24       합계      노원구  2021   121      54    46     13     8    55       2
25       합계      노원구  2022   137      48    54     30     5    63       -
26       합계      은평구  2021   171      63    58     47     3   103       2
27       합계      은평구  2022   152      62    39     50     1   106       3
28       합계     서대문구  2021    69      26    25     17     1    83       3
29       합계     서대문구  2022    80      30    23     27     -    38       -
30       합계      마포구  2021    90      47    38      3     2   213       5
31       합계      마포구  2022    82      45    26      5     6   199       6
32       합계      양천구  2021   129      89    36      3     1   126       7
33       합계      양천구  2022    93      54    22     17     -    82       7
34       합계      강서구  2021   102      41    40     16     5    61       2
35       합계      강서구  2022   119      49    42     27     1    86       2
36       합계      구로구  2021    93      46    36     11     -    88       -
37       합계      구로구  2022    94      43    32     19     -    71       2
38       합계      금천구  2021    61      25    21     11     4    70       -
39       합계      금천구  2022   100      33    38     27     2    43       -
40       합계     영등포구  2021    81      31    37     11     2    66       2
41       합계     영등포구  2022    72      37    23     11     1    68       -
42       합계      동작구  2021   109      81    24      2     2   112       3
43       합계      동작구  2022    68      41    17      9     1   147       2
44       합계      관악구  2021   257     112   132      8     5   319      11
45       합계      관악구  2022   199      74    62     61     2    89       3
46       합계      서초구  2021   133      36    73     22     2    37       3
47       합계      서초구  2022    77      23    26     24     4    45       -
48       합계      강남구  2021    66      34    22      9     1    64       3
49       합계      강남구  2022    92      41    37     14     -    47       1
50       합계      송파구  2021   103      41    46     15     1   100       2
51       합계      송파구  2022    69      35    17     16     1    97       3
52       합계      강동구  2021   166      84    65      5    12   205       5
53       합계      강동구  2022   132      71    49     10     2   136       2

    합계.7   합계.8  합계.9
0    고양이    고양이   고양이
1   입양분양  폐사안락사  계류기증
2    970   1417    67
3    621   1393    64
4     13     80     1
5     15     87     -
6     18     38     -
7     13     33     -
8     82     55     4
9     48     56     -
10    15     62     -
11    11     77     -
12    20     56     -
13    18     76     -
14    26     63     1
15    38     57     1
16    16     75     4
17    25     53     6
18    12     35     -
19     6     37     -
20    13     58     -
21    21     70     -
22    11     43     1
23    18     26     -
24     5     47     1
25     7     56     -
26    15     86     -
27    18     84     1
28    19     60     1
29    15     23     -
30   144     51    13
31   129     53    11
32    55     64     -
33    27     46     2
34    12     46     1
35    13     70     1
36    13     75     -
37    13     56     -
38     6     63     1
39     6     37     -
40    10     53     1
41     7     59     2
42    51     36    22
43    38     84    23
44   268     38     2
45    25     54     7
46     7     27     -
47    10     34     1
48    11     48     2
49     9     37     -
50    16     82     -
51    14     79     1
52   112     76    12
53    77     49     8

/opt/homebrew/anaconda3/envs/aidata/lib/python3.12/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

###(3)텍스트 화일(유기동물보호현황.txt) 읽고 데이터 확인하기

In [12]:
# 변수명 = pd.read_csv(‘파일경로명', 속성들)
txtData = pd.read_csv("유기동물보호현황.csv", encoding="EUC-KR")
print(txtData)

    자치구별(1)  자치구별(2)    시점     합계    합계.1   합계.2   합계.3  합계.4   합계.5    합계.6  \
0   자치구별(1)  자치구별(2)    시점      개       개      개      개     개    고양이     고양이
1   자치구별(1)  자치구별(2)    시점     소계  인도(주인)   입양분양  폐사안락사  계류기증     소계  인도(주인)
2        합계       소계  2021  2,784   1,260  1,110    341    73  2,526      72
3        합계       소계  2022  2,491   1,110    814    536    31  2,134      56
4        합계      종로구  2021     92      24     43     19     6     94       -
5        합계      종로구  2022     79      28     22     29     -    103       1
6        합계       중구  2021     32      20      5      5     2     56       -
7        합계       중구  2022     36      19     10      7     -     47       1
8        합계      용산구  2021    112      80     30      1     1    146       5
9        합계      용산구  2022    118      79     33      5     1    115      11
10       합계      성동구  2021     75      25     36     13     1     77       -
11       합계      성동구  2022     70      34     17     19     -     91       3
12       합계      광진구  2021     73      35     28     10     -     77       1
13       합계      광진구  2022     67      33     27      7     -     96       2
14       합계     동대문구  2021    100      40     47     11     2     90       -
15       합계     동대문구  2022     94      34     41     18     1     99       3
16       합계      중랑구  2021    107      48     41     12     6    109      14
17       합계      중랑구  2022    102      48     35     16     3     84       -
18       합계      성북구  2021    175      64     82     26     3     48       1
19       합계      성북구  2022    115      48     35     32     -     44       1
20       합계      강북구  2021    166      67     62     34     3     72       1
21       합계      강북구  2022    162      56     63     43     -     91       -
22       합계      도봉구  2021    101      47     37     17     -     55       -
23       합계      도봉구  2022     82      45     24     13     -     47       3
24       합계      노원구  2021    121      54     46     13     8     55       2
25       합계      노원구  2022    137      48     54     30     5     63       -
26       합계      은평구  2021    171      63     58     47     3    103       2
27       합계      은평구  2022    152      62     39     50     1    106       3
28       합계     서대문구  2021     69      26     25     17     1     83       3
29       합계     서대문구  2022     80      30     23     27     -     38       -
30       합계      마포구  2021     90      47     38      3     2    213       5
31       합계      마포구  2022     82      45     26      5     6    199       6
32       합계      양천구  2021    129      89     36      3     1    126       7
33       합계      양천구  2022     93      54     22     17     -     82       7
34       합계      강서구  2021    102      41     40     16     5     61       2
35       합계      강서구  2022    119      49     42     27     1     86       2
36       합계      구로구  2021     93      46     36     11     -     88       -
37       합계      구로구  2022     94      43     32     19     -     71       2
38       합계      금천구  2021     61      25     21     11     4     70       -
39       합계      금천구  2022    100      33     38     27     2     43       -
40       합계     영등포구  2021     81      31     37     11     2     66       2
41       합계     영등포구  2022     72      37     23     11     1     68       -
42       합계      동작구  2021    109      81     24      2     2    112       3
43       합계      동작구  2022     68      41     17      9     1    147       2
44       합계      관악구  2021    257     112    132      8     5    319      11
45       합계      관악구  2022    199      74     62     61     2     89       3
46       합계      서초구  2021    133      36     73     22     2     37       3
47       합계      서초구  2022     77      23     26     24     4     45       -
48       합계      강남구  2021     66      34     22      9     1     64       3
49       합계      강남구  2022     92      41     37     14     -     47       1
50       합계      송파구  2021    103      41     46     15     1    100       2
51       합계      송파구  2022     69      35     17     16     1     97       3
52       합계      강동구  2021    166      84     65      5    12    205       5
53       합계      강동구  2022    132      71     49     10     2    136       2

    합계.7   합계.8  합계.9
0    고양이    고양이   고양이
1   입양분양  폐사안락사  계류기증
2    970  1,417    67
3    621  1,393    64
4     13     80     1
5     15     87     -
6     18     38     -
7     13     33     -
8     82     55     4
9     48     56     -
10    15     62     -
11    11     77     -
12    20     56     -
13    18     76     -
14    26     63     1
15    38     57     1
16    16     75     4
17    25     53     6
18    12     35     -
19     6     37     -
20    13     58     -
21    21     70     -
22    11     43     1
23    18     26     -
24     5     47     1
25     7     56     -
26    15     86     -
27    18     84     1
28    19     60     1
29    15     23     -
30   144     51    13
31   129     53    11
32    55     64     -
33    27     46     2
34    12     46     1
35    13     70     1
36    13     75     -
37    13     56     -
38     6     63     1
39     6     37     -
40    10     53     1
41     7     59     2
42    51     36    22
43    38     84    23
44   268     38     2
45    25     54     7
46     7     27     -
47    10     34     1
48    11     48     2
49     9     37     -
50    16     82     -
51    14     79     1
52   112     76    12
53    77     49     8

###(4)tab으로 구분된 텍스트 화일(유기동물보호현황.txt) 읽어오기

In [14]:
# 변수명 = pd.read_csv(파일경로명, 속성들)
# delimiter='구분기호'
# 생략시 ","로 인식
# \t: tab을 열 구분 문자로 인식
txtData = pd.read_csv("유기동물보호현황.txt", delimiter="\t")
txtData

,자치구별(1),자치구별(2),2022,2022.1,2022.2,2022.3,2022.4,2022.5,2022.6,2022.7,2022.8,2022.9,2022.10,2022.11,2022.12,2022.13,2022.14,2022.15
0,자치구별(1),자치구별(2),합계,합계,합계,합계,합계,합계,합계,합계,합계,합계,합계,합계,합계,합계,합계,합계
1,자치구별(1),자치구별(2),소계,개,개,개,개,개,고양이,고양이,고양이,고양이,고양이,기타,기타,기타,기타,기타
2,자치구별(1),자치구별(2),소계,소계,인도(주인),입양분양,폐사안락사,계류기증,소계,인도(주인),입양분양,폐사안락사,계류기증,소계,인도(주인),입양분양,폐사안락사,계류기증
3,합계,소계,4870,2491,1110,814,536,31,2134,56,621,1393,64,245,11,124,105,5
4,합계,종로구,191,79,28,22,29,-,103,1,15,87,-,9,-,6,3,-
5,합계,중구,93,36,19,10,7,-,47,1,13,33,-,10,-,5,5,-
6,합계,용산구,238,118,79,33,5,1,115,11,48,56,-,5,1,3,1,-
7,합계,성동구,165,70,34,17,19,-,91,3,11,77,-,4,-,4,-,-
8,합계,광진구,167,67,33,27,7,-,96,2,18,76,-,4,-,3,1,-
9,합계,동대문구,201,94,34,41,18,1,99,3,38,57,1,8,-,5,3,-
10,합계,중랑구,199,102,48,35,16,3,84,-,25,53,6,13,-,2,11,-
11,합계,성북구,168,115,48,35,32,-,44,1,6,37,-,9,1,7,1,-
12,합계,강북구,270,162,56,63,43,-,91,-,21,70,-,17,1,6,10,-
13,합계,도봉구,137,82,45,24,13,-,47,3,18,26,-,8,1,5,2,-
14,합계,노원구,215,137,48,54,30,5,63,-,7,56,-,15,-,9,6,-
15,합계,은평구,273,152,62,39,50,1,106,3,18,84,1,15,-,8,7,-
16,합계,서대문구,120,80,30,23,27,-,38,-,15,23,-,2,1,-,1,-
17,합계,마포구,286,82,45,26,5,6,199,6,129,53,11,5,1,2,2,-
18,합계,양천구,189,93,54,22,17,-,82,7,27,46,2,14,-,6,8,-
19,합계,강서구,222,119,49,42,27,1,86,2,13,70,1,17,1,8,8,-
20,합계,구로구,180,94,43,32,19,-,71,2,13,56,-,15,-,8,7,-
21,합계,금천구,148,100,33,38,27,2,43,-,6,37,-,5,-,2,3,-
22,합계,영등포구,152,72,37,23,11,1,68,-,7,59,2,12,1,7,4,-
23,합계,동작구,224,68,41,17,9,1,147,2,38,84,23,9,-,6,2,1
24,합계,관악구,298,199,74,62,61,2,89,3,25,54,7,10,1,6,3,-
25,합계,서초구,130,77,23,26,24,4,45,-,10,34,1,8,-,6,2,-
26,합계,강남구,147,92,41,37,14,-,47,1,9,37,-,8,-,3,5,-
27,합계,송파구,173,69,35,17,16,1,97,3,14,79,1,7,2,1,4,-
28,합계,강동구,284,132,71,49,10,2,136,2,77,49,8,16,-,6,6,4

###(5)csv 화일(유기동물보호현황.csv) 읽어오기 (오류생김)

In [15]:
# 변수명 = pd.read_csv('파일경로명', 속성들)
csvData = pd.read_csv("유기동물보호현황.csv", encoding="EUC-KR")
csvData

,자치구별(1),자치구별(2),시점,합계,합계.1,합계.2,합계.3,합계.4,합계.5,합계.6,합계.7,합계.8,합계.9
0,자치구별(1),자치구별(2),시점,개,개,개,개,개,고양이,고양이,고양이,고양이,고양이
1,자치구별(1),자치구별(2),시점,소계,인도(주인),입양분양,폐사안락사,계류기증,소계,인도(주인),입양분양,폐사안락사,계류기증
2,합계,소계,2021,"2,784","1,260","1,110",341,73,"2,526",72,970,"1,417",67
3,합계,소계,2022,"2,491","1,110",814,536,31,"2,134",56,621,"1,393",64
4,합계,종로구,2021,92,24,43,19,6,94,-,13,80,1
5,합계,종로구,2022,79,28,22,29,-,103,1,15,87,-
6,합계,중구,2021,32,20,5,5,2,56,-,18,38,-
7,합계,중구,2022,36,19,10,7,-,47,1,13,33,-
8,합계,용산구,2021,112,80,30,1,1,146,5,82,55,4
9,합계,용산구,2022,118,79,33,5,1,115,11,48,56,-
10,합계,성동구,2021,75,25,36,13,1,77,-,15,62,-
11,합계,성동구,2022,70,34,17,19,-,91,3,11,77,-
12,합계,광진구,2021,73,35,28,10,-,77,1,20,56,-
13,합계,광진구,2022,67,33,27,7,-,96,2,18,76,-
14,합계,동대문구,2021,100,40,47,11,2,90,-,26,63,1
15,합계,동대문구,2022,94,34,41,18,1,99,3,38,57,1
16,합계,중랑구,2021,107,48,41,12,6,109,14,16,75,4
17,합계,중랑구,2022,102,48,35,16,3,84,-,25,53,6
18,합계,성북구,2021,175,64,82,26,3,48,1,12,35,-
19,합계,성북구,2022,115,48,35,32,-,44,1,6,37,-
20,합계,강북구,2021,166,67,62,34,3,72,1,13,58,-
21,합계,강북구,2022,162,56,63,43,-,91,-,21,70,-
22,합계,도봉구,2021,101,47,37,17,-,55,-,11,43,1
23,합계,도봉구,2022,82,45,24,13,-,47,3,18,26,-
24,합계,노원구,2021,121,54,46,13,8,55,2,5,47,1
25,합계,노원구,2022,137,48,54,30,5,63,-,7,56,-
26,합계,은평구,2021,171,63,58,47,3,103,2,15,86,-
27,합계,은평구,2022,152,62,39,50,1,106,3,18,84,1
28,합계,서대문구,2021,69,26,25,17,1,83,3,19,60,1
29,합계,서대문구,2022,80,30,23,27,-,38,-,15,23,-
30,합계,마포구,2021,90,47,38,3,2,213,5,144,51,13
31,합계,마포구,2022,82,45,26,5,6,199,6,129,53,11
32,합계,양천구,2021,129,89,36,3,1,126,7,55,64,-
33,합계,양천구,2022,93,54,22,17,-,82,7,27,46,2
34,합계,강서구,2021,102,41,40,16,5,61,2,12,46,1
35,합계,강서구,2022,119,49,42,27,1,86,2,13,70,1
36,합계,구로구,2021,93,46,36,11,-,88,-,13,75,-
37,합계,구로구,2022,94,43,32,19,-,71,2,13,56,-
38,합계,금천구,2021,61,25,21,11,4,70,-,6,63,1
39,합계,금천구,2022,100,33,38,27,2,43,-,6,37,-
40,합계,영등포구,2021,81,31,37,11,2,66,2,10,53,1
41,합계,영등포구,2022,72,37,23,11,1,68,-,7,59,2
42,합계,동작구,2021,109,81,24,2,2,112,3,51,36,22
43,합계,동작구,2022,68,41,17,9,1,147,2,38,84,23
44,합계,관악구,2021,257,112,132,8,5,319,11,268,38,2
45,합계,관악구,2022,199,74,62,61,2,89,3,25,54,7
46,합계,서초구,2021,133,36,73,22,2,37,3,7,27,-
47,합계,서초구,2022,77,23,26,24,4,45,-,10,34,1
48,합계,강남구,2021,66,34,22,9,1,64,3,11,48,2
49,합계,강남구,2022,92,41,37,14,-,47,1,9,37,-
50,합계,송파구,2021,103,41,46,15,1,100,2,16,82,-
51,합계,송파구,2022,69,35,17,16,1,97,3,14,79,1
52,합계,강동구,2021,166,84,65,5,12,205,5,112,76,12
53,합계,강동구,2022,132,71,49,10,2,136,2,77,49,8

###(6)csv 화일(유기동물보호현황.csv) 읽어오기

- Encoding 방식 설정

In [16]:
# 변수명 = pd.read_csv(파일경로명, 속성들)

# - encoding=‘인코딩방식’: 한글이 깨져서 보일 경우 인코딩 방식 설정
# - EUC_KR(한글이 포함된 일반적인 경우)/cp949(MS office에서 저장한 파일 형식)

###(7)데이터 정보 확인하기
데이터타입, 각 행열의 개수, 누락데이터 수등 확인한 후 다음 물음에 답하세요.

- 행과 열은 어떻게 구성되어 있는가?
- 열의 이름들은 무엇인가?
- 범주형 데이터와 수치형 데이터는 무엇인가?

In [17]:
# 변수명.info()
csvData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 13 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   자치구별(1)  54 non-null     object
 1   자치구별(2)  54 non-null     object
 2   시점       54 non-null     object
 3   합계       54 non-null     object
 4   합계.1     54 non-null     object
 5   합계.2     54 non-null     object
 6   합계.3     54 non-null     object
 7   합계.4     54 non-null     object
 8   합계.5     54 non-null     object
 9   합계.6     54 non-null     object
 10  합계.7     54 non-null     object
 11  합계.8     54 non-null     object
 12  합계.9     54 non-null     object
dtypes: object(13)
memory usage: 5.6+ KB

###(8) csv 화일(유기동물보호현황.csv)에서 특정 행을 header로 설정하여 읽어오기

- 2번째 행을 열이름으로 설정하기
- 읽어온 데이터를 csvData 변수에 저장하기
- 상위 5개의 데이터 확인하기

In [19]:
# 변수명 = pd.read_csv(파일경로명, header=[])
# header=[행번호] : 위에서 몇 째줄 부터 읽어올지 지정(줄 수는 0부터 시작)
# header=[2] : 2번째 행을 열이름으로 설정

csvData = pd.read_csv("유기동물보호현황.csv", encoding="EUC-KR", header=[2])
csvData.head()

,자치구별(1),자치구별(2),시점,소계,인도(주인),입양분양,폐사안락사,계류기증,소계.1,인도(주인).1,입양분양.1,폐사안락사.1,계류기증.1
0,합계,소계,2021,"2,784","1,260","1,110",341,73,"2,526",72,970,"1,417",67
1,합계,소계,2022,"2,491","1,110",814,536,31,"2,134",56,621,"1,393",64
2,합계,종로구,2021,92,24,43,19,6,94,-,13,80,1
3,합계,종로구,2022,79,28,22,29,-,103,1,15,87,-
4,합계,중구,2021,32,20,5,5,2,56,-,18,38,-

###(9) 데이터의 정보 확인하기

- 행과 열은 어떻게 구성되어 있는가?
- 열의 이름들은 무엇인가?
- 범주형 데이터와 수치형 데이터는 무엇인가?

###(10)csv 화일(유기동물보호현황.csv)에서 2개의 행을 header로 읽어오기

- 1번째와 2번째 행을 열이름으로 설정
- 읽어온 데이터를 data 변수에 저장
- 상위 5개의 데이터 확인하기

In [20]:
# header=[1, 2] : 1,2번째 행을 열이름으로 설정

data = pd.read_csv("유기동물보호현황.csv", encoding="EUC-KR", header=[1, 2])
data.head()

  자치구별(1) 자치구별(2)    시점      개                             고양이              \
  자치구별(1) 자치구별(2)    시점     소계 인도(주인)   입양분양 폐사안락사 계류기증     소계 인도(주인) 입양분양
0      합계      소계  2021  2,784  1,260  1,110   341   73  2,526     72  970
1      합계      소계  2022  2,491  1,110    814   536   31  2,134     56  621
2      합계     종로구  2021     92     24     43    19    6     94      -   13
3      합계     종로구  2022     79     28     22    29    -    103      1   15
4      합계      중구  2021     32     20      5     5    2     56      -   18


   폐사안락사 계류기증
0  1,417   67
1  1,393   64
2     80    1
3     87    -
4     38    -

###(11) 데이터의 정보 확인하기

- 행과 열은 어떻게 구성되어 있는가?
- 열의 이름들은 무엇인가?
- 범주형 데이터와 수치형 데이터는 무엇인가?

###(12)csv 화일(유기동물보호현황.csv) 읽어오기

- 1번째와 2번째 행을 열이름으로 설정
- 숫자에 ','가 있는 데이터의 ','는 모두 제거
- 상위 5개의 데이터 확인하기

In [22]:
# 변수명 = pd.read_csv(파일경로명, 속성들)
# thousands=',' : ','가 포함된 문자열 데이터에서 ','를 삭제하고 숫자형 데이터를 변경

csvData = pd.read_csv("유기동물보호현황.csv", encoding="EUC-KR", thousands=",")
csvData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 13 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   자치구별(1)  54 non-null     object
 1   자치구별(2)  54 non-null     object
 2   시점       54 non-null     object
 3   합계       54 non-null     object
 4   합계.1     54 non-null     object
 5   합계.2     54 non-null     object
 6   합계.3     54 non-null     object
 7   합계.4     54 non-null     object
 8   합계.5     54 non-null     object
 9   합계.6     54 non-null     object
 10  합계.7     54 non-null     object
 11  합계.8     54 non-null     object
 12  합계.9     54 non-null     object
dtypes: object(13)
memory usage: 5.6+ KB

###(13) 데이터의 정보 확인하기

- 행과 열은 어떻게 구성되어 있는가?
- 열의 이름들은 무엇인가?
- 범주형 데이터와 수치형 데이터는 무엇인가?

##3.데이터를 화일에 저장하기

###(1) 데이터를 csv 화일(변환후.csv)로 저장하기

In [26]:
# 변수명.to_csv('화일명')
csvData.to_csv("test.csv")

###(2) 데이터를 excel 화일(변환후.xlsx)로 저장하기

In [27]:
# 변수명.to_excel('화일명')
csvData.to_excel("test.xlsx")